if (!hasInterface) exitWith {};
missionNamespace setVariable ["CTHUD_runtimeEnabled", false];
missionNamespace setVariable ["CTHUD_defaultHudHidden", false];
missionNamespace setVariable ["CTHUD_savedHudState", []];
missionNamespace setVariable ["CTHUD_lastPowerState", false];
missionNamespace setVariable ["CTHUD_startupStartedAt", -1];
missionNamespace setVariable ["CTHUD_startupDuration", 1.35];
missionNamespace setVariable ["CTHUD_startupFadeDuration", 0.32];
missionNamespace setVariable ["CTHUD_activeDisplayClass", ""];
[] call CTHUD_fnc_registerAceActions;
[] spawn CTHUD_fnc_initPlayerHUD;
